FROM ghcr.io/ananda-aropa/aaropa_rootfs_base:latest AS final

COPY template /
COPY packages /

RUN apt update && apt full-upgrade -y --allow-unauthenticated

# Clean up cache & files
RUN apt autoclean && rm -rf /var/lib/apt/lists/*